### ISSUE TITLE
Have no Windows

### ISSUE THREAD

**Issue by AhrendsSchmidt** [Kara-4search/MappingInjection_CSharp#1]
When I run the program, there is no pop-up window :(
![image](https://user-images.githubusercontent.com/33677393/130604619-83e070d4-605b-4aea-b281-2a8c7c94ecfc.png)

**Comment by Kara-4search** [comment]
> When I run the program, there is no pop-up window :(
> ![image](https://user-images.githubusercontent.com/33677393/130604619-83e070d4-605b-4aea-b281-2a8c7c94ecfc.png)

There are some details you need2 tell me first
1. The process name you choose to inject
2. If the process that you want to inject is a x64 process
3. Win10 version.

**Comment by AhrendsSchmidt** [comment]
1、powershell
2、yes
3、win10 pro

**Comment by Kara-4search** [comment]
> 1、powershell
> 2、yes
> 3、win10 pro

Its works fine for me, you could try set the process name to explorer

**Comment by Kara-4search** [comment]
I ve found the reason cause this problem
I probably change the code after I test it，and the code were uploaded to github is not the original version
I ve fixed the problem，update later.
Sry for the  bugs @Pwn0x01

**Comment by Kara-4search** [comment]
feel free to test it again

**Comment by Kara-4search** [comment]
#1
